# Use the latest version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build:
    # Define the Docker image to use for the job.
    docker:
      - image: cimg/openjdk:19.0.2
    # Define the steps to run in the job.
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y ant maven
      - run:
          name: Build project
          command: |
            cd dependencies
            ant
            cd ..
            mvn clean package

# Define a workflow to run the build job.
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
